### ISSUE TITLE
NegativeArraySizeException in DiskBasedCache

### ISSUE THREAD

**Issue by hoeggi** [sensorberg-dev/android-sdk#10]
I'm getting this crash recently right after application start:

Fatal Exception: java.lang.NegativeArraySizeException: -818 at com.android.sensorbergVolley.toolbox.DiskBasedCache.streamToBytes(DiskBasedCache.java:322)
       at com.android.sensorbergVolley.toolbox.DiskBasedCache.get(DiskBasedCache.java:118)
       at com.android.sensorbergVolley.CacheDispatcher.run(CacheDispatcher.java:100)

I'm on:
sdk: 1.0.4
boostrapper: 2.0.0

Crash happened on Android 5.0.1 and 6.0.1 on a Galaxy S4 and a Nexus 5

**Comment by cemhan** [comment]
Fatal Exception: java.lang.NegativeArraySizeException: -943
       at com.android.volley.toolbox.DiskBasedCache.streamToBytes(SourceFile:322)
       at com.android.volley.toolbox.DiskBasedCache.get(SourceFile:118)
       at com.android.volley.CacheDispatcher.run(SourceFile:100)

http://crashes.to/s/617b4b4b939

**Comment by hoeggi** [comment]
Getting this error on more Devices now:
Samsunng Galaxy S5 mini with 4.4.2
Sony Experia V with 4.3

**Comment by falkorichter** [comment]
Fixed with a simple check in https://github.com/sensorberg-dev/android-sdk/tree/hotfix/volley_negative_array

**Comment by abhaymaniyar** [comment]
Hey @falkorichter! Can you please post another link for the hotfix? This link is not working for me.
