### ISSUE TITLE
Crash when stopping Bluetooth Scann

### ISSUE THREAD

**Issue by hoeggi** [sensorberg-dev/android-sdk#11]
I'm getting lots of this crashes lately:

Fatal Exception: java.lang.NullPointerException
       at android.bluetooth.BluetoothAdapter$GattCallbackWrapper.stopLeScan(BluetoothAdapter.java:1658)
       at android.bluetooth.BluetoothAdapter.stopLeScan(BluetoothAdapter.java:1602)
       at com.sensorberg.sdk.internal.AndroidPlatform.stopLeScan(SourceFile:443)
       at com.sensorberg.sdk.scanner.AbstractScanner.handleMessage(SourceFile:186)
       at com.sensorberg.sdk.internal.AndroidHandler$LooperThread$StaticHandler.handleMessage(SourceFile:128)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at com.sensorberg.sdk.internal.AndroidHandler$LooperThread.run(SourceFile:115)

This happens on mostly Samsung devices from 4.3 to 5.0.

**Comment by falkorichter** [comment]
over 300 times in an Austrian app.

**Comment by falkorichter** [comment]
I worked around this by catching this system bug: https://github.com/sensorberg-dev/android-sdk/tree/hotfix/start_stop_scan_scrashes

**Comment by labibmezghanni** [comment]
@falkorichter 

Which SDK should we use to get this bug fix?

We are using those as recommended in the tutorial

compile 'com.sensorberg.sdk:android-sdk-bootstrapper:2.0.0'
compile 'com.sensorberg.sdk:android-sdk:1.0.4'

Labib from COUPIES

**Comment by skraynick** [comment]
@labibmezghanni 
Sorry for the delay. We have a newer version of the SDK listed on Jcenter 1.0.5RC4 . You can try to use the newer version.  If the problem persists, please let me know and I will look into it. 

Sarah
