### ISSUE TITLE
CRASH GoogleApiClient is not connected yet

### ISSUE THREAD

**Issue by QponyDev** [sensorberg-dev/android-sdk#127]
### Description: 
`Fatal Exception: java.lang.IllegalStateException: GoogleApiClient is not connected yet.
       at com.google.android.gms.internal.zzaar.zzb(Unknown Source)
       at com.google.android.gms.internal.zzaav.zzb(Unknown Source)
       at com.google.android.gms.internal.zzaat.zzb(Unknown Source)
       at com.google.android.gms.internal.zzary.removeLocationUpdates(Unknown Source)
       at com.sensorberg.sdk.location.GeofenceManager.removeLocationUpdates(GeofenceManager.java:430)
       at com.sensorberg.sdk.location.GeofenceManager.disable(GeofenceManager.java:93)
       at com.sensorberg.sdk.location.GeofenceManager.onFencesChanged(GeofenceManager.java:107)
       at com.sensorberg.sdk.InternalApplicationBootstrapper.proximityUUIDListUpdated(InternalApplicationBootstrapper.java:409)
       at com.sensorberg.sdk.internal.transport.RetrofitApiTransport$4.onSuccess(RetrofitApiTransport.java:263)
       at com.sensorberg.sdk.internal.transport.RetrofitApiTransport$4.onResponse(RetrofitApiTransport.java:251)`

**Comment by stanleyguevara** [comment]
It was uncaught exception when removing geofences from play services.
Should be fixed now by #128, coming in next release.
