### ISSUE TITLE
Bug caused by realm version

### ISSUE THREAD

**Issue by btwarog** [sensorberg-dev/android-sdk#35]
Hi, realm version you're using in your SDK is causing a lots of crashes, below is log of the crash:
>Fatal Exception: java.lang.RuntimeException: Unspecified exception. mremap(): failed: Function not implemented in io_realm_internal_SharedGroup.cpp line 100
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:58)
       at io.realm.Realm.<init>(Realm.java:199)
       at io.realm.Realm.createAndValidate(Realm.java:516)
       at io.realm.Realm.create(Realm.java:480)
       at io.realm.Realm.getInstance(Realm.java:397)
       at io.realm.Realm.getInstance(Realm.java:359)
       at com.sensorberg.sdk.scanner.BeaconActionHistoryPublisher.handleMessage(BeaconActionHistoryPublisher.java:64)
       at com.sensorberg.sdk.internal.AndroidHandler$LooperThread$StaticHandler.handleMessage(AndroidHandler.java:128)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at com.sensorberg.sdk.internal.AndroidHandler$LooperThread.run(AndroidHandler.java:115)Fatal Exception: java.lang.RuntimeException: Unspecified exception. mremap(): failed: Function not implemented in io_realm_internal_SharedGroup.cpp line 100
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:58)
       at io.realm.Realm.<init>(Realm.java:199)
       at io.realm.Realm.createAndValidate(Realm.java:516)
       at io.realm.Realm.create(Realm.java:480)
       at io.realm.Realm.getInstance(Realm.java:397)
       at io.realm.Realm.getInstance(Realm.java:359)
       at com.sensorberg.sdk.scanner.BeaconActionHistoryPublisher.handleMessage(BeaconActionHistoryPublisher.java:64)
       at com.sensorberg.sdk.internal.AndroidHandler$LooperThread$StaticHandler.handleMessage(AndroidHandler.java:128)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at com.sensorberg.sdk.internal.AndroidHandler$LooperThread.run(AndroidHandler.java:115)
>

The solution of the problem is upgrading realm version to at least **0.84** according to this https://github.com/realm/realm-java/issues/1380

**Comment by skraynick** [comment]
@btwarog try our latest sdk... 1.2.0.. We have refactored out realm.; you shouldn't have any further issues. Let me know if you have any further questions or problems.

**Comment by btwarog** [comment]
@skraynick ok i will updated and notice you if bug still occurs

**Comment by mrsasha** [comment]
@btwarog Hi Bartolomej, we have actually changed our feature list for 1.2.0 so the realm is still there. 

What we did, though, is to publish an 2.0.0RC1, where we're using Sugar instead of Realm, but there are also some other changes, one or two which are breaking. You can check out the develop branch and see the changes in our dev-app example.

Sorry about this.

**Comment by mrsasha** [comment]
@btwarog Hi Bartolomej, in the 2.0.0RC6 we removed Sugar, we now use SharedPrefs for some local persistence. Hopefully this helps.

**Comment by mrsasha** [comment]
@btwarog We have also published final 2.0.0 release, so we're gonna close this issue.  Let us know if you have any other problems.
