### ISSUE TITLE
AndroidBluetoothPlatform.stopLeScan bug

### ISSUE THREAD

**Issue by btwarog** [sensorberg-dev/android-sdk#65]
Hi,

We are getting huge amount of bug reports from our sensorberg android integration with the following stack trace:

> Fatal Exception: java.lang.IllegalStateException: BT Adapter is not turned ON
       at android.bluetooth.le.BluetoothLeUtils.checkAdapterStateOn(BluetoothLeUtils.java:136)
       at android.bluetooth.le.BluetoothLeScanner.stopScan(BluetoothLeScanner.java:169)
       at android.bluetooth.BluetoothAdapter.stopLeScan(BluetoothAdapter.java:2405)
       at com.sensorberg.sdk.internal.AndroidBluetoothPlatform.stopLeScan(AndroidBluetoothPlatform.java:85)
       at com.sensorberg.sdk.scanner.AbstractScanner.handleMessage(AbstractScanner.java:217)
       at com.sensorberg.sdk.internal.AndroidHandler$LooperThread$StaticHandler.handleMessage(AndroidHandler.java:129)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:234)
       at com.sensorberg.sdk.internal.AndroidHandler$LooperThread.run(AndroidHandler.java:116)

The version of library that we're currently using is 2.0.4.

Thanks,
Bartek.

**Comment by falkorichter** [comment]
@btwarog Sounds like something we fixed in [2.0.6](https://github.com/sensorberg-dev/android-sdk/releases/tag/v2.0.6)

**Comment by btwarog** [comment]
O, I didn't notice that. I will upgrade version and in case of reappearing of that issue will notice you
